### ISSUE TITLE
I compiled it and now?

### ISSUE THREAD

**Issue by katzendrama** [MCProHosting/DynamicBungee#2]
Hello i have compiled DynamicBungee what must i do to use it on Windows do i need Redis.. Apache... or how can i use it

**Comment by katzendrama** [comment]
The error in the BungeeCord Console:
20:54:32 [WARNUNG] Error enabling plugin DynamicBungee
java.lang.ClassNotFoundException: com.mcprohosting.plugins.dynamicbungee.Dynamic
Bungee
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader
.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.
java:27)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:
297)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:2
05)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:247)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
20:54:32 [INFORMATION] Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:
"b3d15d5":1078 by SpigotMC

**Comment by MattJustMatt** [comment]
Hi there! Unfortunately this is an extremely old project and we're no longer providing maintenance on it. :(
